In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("sales_table.csv")

In [4]:
df

,Order ID,Category,Sub-Category,Segment,Sales,Profit,Quantity
0,1001,furniture,tables,consumer,909.0,2537.0,9.0
1,1002,FURNITURE,CHAIRS,CORPORATE,2786.0,2516.0,4.0
2,1003,furniture,tables,corporate,9435.0,-144.0,19.0
3,1004,office supplies,storage,consumer,988.0,-117.0,NaN
4,1005,FURNITURE,CHAIRS,HOME OFFICE,934.0,1798.0,7.0
5,1006,furniture,tables,corporate,9428.0,1218.0,8.0
6,1007,office supplies,storage,HOME OFFICE,NaN,2815.0,1.0
7,1008,FURNITURE,CHAIRS,corporate,7424.0,893.0,9.0
8,1009,FURNITURE,CHAIRS,CORPORATE,6014.0,-82.0,3.0
9,1010,office supplies,storage,consumer,6381.0,2971.0,12.0
10,1011,TECHNOLOGY,ACCESSORIES,home office,1211.0,2488.0,15.0
11,1012,TECHNOLOGY,ACCESSORIES,consumer,6701.0,-178.0,18.0
12,1013,technology,phones,corporate,6425.0,1864.0,7.0
13,1014,furniture,tables,consumer,1250.0,2208.0,8.0
14,1015,technology,phones,consumer,4314.0,-87.0,13.0
15,1016,technology,phones,Consumer,6477.0,166.0,12.0
16,1017,technology,phones,CORPORATE,4874.0,2374.0,3.0
17,1018,TECHNOLOGY,ACCESSORIES,corporate,3303.0,1687.0,8.0
18,1019,FURNITURE,CHAIRS,Consumer,6716.0,605.0,18.0
19,1020,FURNITURE,CHAIRS,corporate,5813.0,2952.0,2.0
20,1021,FURNITURE,CHAIRS,consumer,5668.0,1143.0,9.0
21,1022,office supplies,binders,CORPORATE,9792.0,2440.0,11.0
22,1023,FURNITURE,CHAIRS,corporate,8679.0,NaN,15.0
23,1024,FURNITURE,CHAIRS,home office,2787.0,510.0,18.0
24,1025,TECHNOLOGY,ACCESSORIES,home office,7519.0,1890.0,13.0
25,1026,technology,phones,CORPORATE,2766.0,1587.0,16.0
26,1027,office supplies,binders,consumer,2296.0,NaN,6.0
27,1028,furniture,tables,Consumer,NaN,NaN,13.0
28,1029,TECHNOLOGY,ACCESSORIES,Consumer,9169.0,529.0,18.0
29,1030,office supplies,binders,corporate,2376.0,2292.0,NaN
30,1031,technology,phones,corporate,6073.0,-44.0,10.0
31,1032,office supplies,storage,CORPORATE,7933.0,-487.0,9.0
32,1033,TECHNOLOGY,ACCESSORIES,CORPORATE,8817.0,-65.0,10.0
33,1034,furniture,tables,HOME OFFICE,3758.0,126.0,12.0
34,1035,FURNITURE,CHAIRS,HOME OFFICE,9189.0,-498.0,20.0
35,1036,technology,phones,Consumer,819.0,-42.0,12.0
36,1037,technology,phones,CORPORATE,1449.0,486.0,19.0
37,1038,office supplies,binders,consumer,8462.0,2842.0,3.0
38,1039,TECHNOLOGY,ACCESSORIES,CORPORATE,2603.0,2202.0,16.0
39,1040,TECHNOLOGY,ACCESSORIES,CORPORATE,4842.0,1661.0,20.0
40,1041,office supplies,storage,CORPORATE,9335.0,2593.0,7.0
41,1042,furniture,tables,home office,7037.0,2251.0,12.0
42,1043,office supplies,storage,HOME OFFICE,NaN,-5.0,8.0
43,1044,FURNITURE,CHAIRS,consumer,6039.0,-414.0,19.0
44,1045,TECHNOLOGY,ACCESSORIES,CORPORATE,4108.0,-471.0,3.0
45,1046,furniture,tables,corporate,1464.0,437.0,3.0
46,1047,office supplies,binders,home office,1660.0,1605.0,NaN
47,1048,technology,phones,corporate,8453.0,377.0,18.0
48,1049,FURNITURE,CHAIRS,corporate,9855.0,1860.0,16.0
49,1050,FURNITURE,CHAIRS,Consumer,7169.0,279.0,4.0

In [6]:
df.shape

(50, 7)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      50 non-null     int64
 1   Category      50 non-null     object
 2   Sub-Category  50 non-null     object
 3   Segment       50 non-null     object
 4   Sales         47 non-null     float64
 5   Profit        47 non-null     float64
 6   Quantity      47 non-null     float64
dtypes: float64(3), int64(1), object(3)
memory usage: 2.9+ KB

In [12]:
df.describe()

         Order ID        Sales       Profit   Quantity
count    50.00000    47.000000    47.000000  47.000000
mean   1025.50000  5351.063830  1139.744681  10.978723
std      14.57738  2962.622431  1145.804435   5.612445
min    1001.00000   819.000000  -498.000000   1.000000
25%    1013.25000  2684.500000   -23.500000   7.000000
50%    1025.50000  6014.000000  1143.000000  11.000000
75%    1037.75000  7726.000000  2229.500000  16.000000
max    1050.00000  9855.000000  2971.000000  20.000000

In [13]:
df.head()

,Order ID,Category,Sub-Category,Segment,Sales,Profit,Quantity
0,1001,furniture,tables,consumer,909.0,2537.0,9.0
1,1002,FURNITURE,CHAIRS,CORPORATE,2786.0,2516.0,4.0
2,1003,furniture,tables,corporate,9435.0,-144.0,19.0
3,1004,office supplies,storage,consumer,988.0,-117.0,NaN
4,1005,FURNITURE,CHAIRS,HOME OFFICE,934.0,1798.0,7.0

In [14]:
df.tail()

,Order ID,Category,Sub-Category,Segment,Sales,Profit,Quantity
45,1046,furniture,tables,corporate,1464.0,437.0,3.0
46,1047,office supplies,binders,home office,1660.0,1605.0,NaN
47,1048,technology,phones,corporate,8453.0,377.0,18.0
48,1049,FURNITURE,CHAIRS,corporate,9855.0,1860.0,16.0
49,1050,FURNITURE,CHAIRS,Consumer,7169.0,279.0,4.0

In [15]:
df=pd.read_excel("financial_practice.xlsx")

In [16]:
df

,Transaction_ID,Date,Customer,Product,Category,Quantity,Sales_Amount,Profit,Payment_Mode
0,1001,2026-01-01,Anu,Laptop,Electronics,2,90000,12000,UPI
1,1002,2026-01-02,Rahul,Mobile,Electronics,1,35000,5000,Card
2,1003,2026-01-03,Meena,Tablet,Electronics,3,45000,7000,Cash
3,1004,2026-01-04,Arjun,Monitor,Electronics,2,30000,4500,UPI
4,1005,2026-01-05,Priya,Keyboard,Accessories,5,7500,1500,Card
5,1006,2026-01-06,Vishnu,Mouse,Accessories,4,4000,800,Cash
6,1007,2026-01-07,Neha,Printer,Office,1,18000,3000,UPI
7,1008,2026-01-08,Akhil,Laptop,Electronics,1,55000,8000,Card
8,1009,2026-01-09,Sneha,Mobile,Electronics,2,36000,5500,UPI
9,1010,2026-01-10,Rohan,Tablet,Electronics,3,42000,6500,Cash
10,1011,2026-01-11,Diya,Monitor,Electronics,2,28000,4200,Card
11,1012,2026-01-12,Kiran,Keyboard,Accessories,6,9000,1800,UPI
12,1013,2026-01-13,Asha,Mouse,Accessories,5,5000,1000,Cash
13,1014,2026-01-14,Nikhil,Printer,Office,2,22000,3500,Card
14,1015,2026-01-15,Pooja,Laptop,Electronics,1,60000,9000,UPI
15,1016,2026-01-16,Manu,Mobile,Electronics,2,38000,6000,Card
16,1017,2026-01-17,Lakshmi,Tablet,Electronics,4,48000,7500,Cash
17,1018,2026-01-18,Aditya,Monitor,Electronics,1,32000,4800,UPI
18,1019,2026-01-19,Anjali,Keyboard,Accessories,5,8000,1600,Card
19,1020,2026-01-20,Suresh,Mouse,Accessories,3,4500,900,Cash
20,1021,2026-01-21,Divya,Printer,Office,2,20000,3200,UPI
21,1022,2026-01-22,Vivek,Laptop,Electronics,1,70000,10000,Card
22,1023,2026-01-23,Reshma,Mobile,Electronics,2,34000,5200,Cash
23,1024,2026-01-24,Hari,Tablet,Electronics,3,46000,7000,UPI
24,1025,2026-01-25,Amal,Monitor,Electronics,2,29000,4300,Card

In [17]:
df.shape

(25, 9)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction_ID  25 non-null     int64
 1   Date            25 non-null     object
 2   Customer        25 non-null     object
 3   Product         25 non-null     object
 4   Category        25 non-null     object
 5   Quantity        25 non-null     int64
 6   Sales_Amount    25 non-null     int64
 7   Profit          25 non-null     int64
 8   Payment_Mode    25 non-null     object
dtypes: int64(4), object(5)
memory usage: 1.9+ KB

In [20]:
df.describe()

       Transaction_ID  Quantity  Sales_Amount        Profit
count       25.000000  25.00000     25.000000     25.000000
mean      1013.000000   2.60000  32640.000000   4952.000000
std          7.359801   1.47196  21737.314308   2973.090424
min       1001.000000   1.00000   4000.000000    800.000000
25%       1007.000000   2.00000  18000.000000   3000.000000
50%       1013.000000   2.00000  32000.000000   4800.000000
75%       1019.000000   3.00000  45000.000000   7000.000000
max       1025.000000   6.00000  90000.000000  12000.000000

In [21]:
df.head()

,Transaction_ID,Date,Customer,Product,Category,Quantity,Sales_Amount,Profit,Payment_Mode
0,1001,2026-01-01,Anu,Laptop,Electronics,2,90000,12000,UPI
1,1002,2026-01-02,Rahul,Mobile,Electronics,1,35000,5000,Card
2,1003,2026-01-03,Meena,Tablet,Electronics,3,45000,7000,Cash
3,1004,2026-01-04,Arjun,Monitor,Electronics,2,30000,4500,UPI
4,1005,2026-01-05,Priya,Keyboard,Accessories,5,7500,1500,Card

In [22]:
df.tail()

,Transaction_ID,Date,Customer,Product,Category,Quantity,Sales_Amount,Profit,Payment_Mode
20,1021,2026-01-21,Divya,Printer,Office,2,20000,3200,UPI
21,1022,2026-01-22,Vivek,Laptop,Electronics,1,70000,10000,Card
22,1023,2026-01-23,Reshma,Mobile,Electronics,2,34000,5200,Cash
23,1024,2026-01-24,Hari,Tablet,Electronics,3,46000,7000,UPI
24,1025,2026-01-25,Amal,Monitor,Electronics,2,29000,4300,Card

In [23]:
df=pd.read_json("financial_practice_json")

In [24]:
df

,Transaction_ID,Date,Customer,Product,Category,Quantity,Sales_Amount,Profit,Payment_Mode
0,1001,2026-01-01,Anu,Laptop,Electronics,2,90000,12000,UPI
1,1002,2026-01-02,Rahul,Mobile,Electronics,1,35000,5000,Card
2,1003,2026-01-03,Meena,Tablet,Electronics,3,45000,7000,Cash
3,1004,2026-01-04,Arjun,Monitor,Electronics,2,30000,4500,UPI
4,1005,2026-01-05,Priya,Keyboard,Accessories,5,7500,1500,Card
5,1006,2026-01-06,Vishnu,Mouse,Accessories,4,4000,800,Cash
6,1007,2026-01-07,Neha,Printer,Office,1,18000,3000,UPI
7,1008,2026-01-08,Akhil,Laptop,Electronics,1,55000,8000,Card
8,1009,2026-01-09,Sneha,Mobile,Electronics,2,36000,5500,UPI
9,1010,2026-01-10,Rohan,Tablet,Electronics,3,42000,6500,Cash
10,1011,2026-01-11,Diya,Monitor,Electronics,2,28000,4200,Card
11,1012,2026-01-12,Kiran,Keyboard,Accessories,6,9000,1800,UPI
12,1013,2026-01-13,Asha,Mouse,Accessories,5,5000,1000,Cash
13,1014,2026-01-14,Nikhil,Printer,Office,2,22000,3500,Card
14,1015,2026-01-15,Pooja,Laptop,Electronics,1,60000,9000,UPI
15,1016,2026-01-16,Manu,Mobile,Electronics,2,38000,6000,Card
16,1017,2026-01-17,Lakshmi,Tablet,Electronics,4,48000,7500,Cash
17,1018,2026-01-18,Aditya,Monitor,Electronics,1,32000,4800,UPI
18,1019,2026-01-19,Anjali,Keyboard,Accessories,5,8000,1600,Card
19,1020,2026-01-20,Suresh,Mouse,Accessories,3,4500,900,Cash
20,1021,2026-01-21,Divya,Printer,Office,2,20000,3200,UPI
21,1022,2026-01-22,Vivek,Laptop,Electronics,1,70000,10000,Card
22,1023,2026-01-23,Reshma,Mobile,Electronics,2,34000,5200,Cash
23,1024,2026-01-24,Hari,Tablet,Electronics,3,46000,7000,UPI
24,1025,2026-01-25,Amal,Monitor,Electronics,2,29000,4300,Card

In [25]:
df.shape

(25, 9)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction_ID  25 non-null     int64
 1   Date            25 non-null     datetime64[ns]
 2   Customer        25 non-null     object
 3   Product         25 non-null     object
 4   Category        25 non-null     object
 5   Quantity        25 non-null     int64
 6   Sales_Amount    25 non-null     int64
 7   Profit          25 non-null     int64
 8   Payment_Mode    25 non-null     object
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 1.9+ KB

In [29]:
df.describe()

,Transaction_ID,Date,Quantity,Sales_Amount,Profit
count,25.000000,25,25.00000,25.000000,25.000000
mean,1013.000000,2026-01-13 00:00:00,2.60000,32640.000000,4952.000000
min,1001.000000,2026-01-01 00:00:00,1.00000,4000.000000,800.000000
25%,1007.000000,2026-01-07 00:00:00,2.00000,18000.000000,3000.000000
50%,1013.000000,2026-01-13 00:00:00,2.00000,32000.000000,4800.000000
75%,1019.000000,2026-01-19 00:00:00,3.00000,45000.000000,7000.000000
max,1025.000000,2026-01-25 00:00:00,6.00000,90000.000000,12000.000000
std,7.359801,NaN,1.47196,21737.314308,2973.090424

In [30]:
df.head()

,Transaction_ID,Date,Customer,Product,Category,Quantity,Sales_Amount,Profit,Payment_Mode
0,1001,2026-01-01,Anu,Laptop,Electronics,2,90000,12000,UPI
1,1002,2026-01-02,Rahul,Mobile,Electronics,1,35000,5000,Card
2,1003,2026-01-03,Meena,Tablet,Electronics,3,45000,7000,Cash
3,1004,2026-01-04,Arjun,Monitor,Electronics,2,30000,4500,UPI
4,1005,2026-01-05,Priya,Keyboard,Accessories,5,7500,1500,Card

In [31]:
df.tail()

,Transaction_ID,Date,Customer,Product,Category,Quantity,Sales_Amount,Profit,Payment_Mode
20,1021,2026-01-21,Divya,Printer,Office,2,20000,3200,UPI
21,1022,2026-01-22,Vivek,Laptop,Electronics,1,70000,10000,Card
22,1023,2026-01-23,Reshma,Mobile,Electronics,2,34000,5200,Cash
23,1024,2026-01-24,Hari,Tablet,Electronics,3,46000,7000,UPI
24,1025,2026-01-25,Amal,Monitor,Electronics,2,29000,4300,Card