In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("financial_transactions.csv")

In [4]:
df

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region
0,1,2026-07-08,Anu,Electronics,Laptop,5,167990,21688,Net Banking,North
1,2,2026-03-01,Nikhil,Stationery,File,1,111,11,Net Banking,North
2,3,2026-05-31,Akhil,Stationery,Pen,9,8181,1051,Cash,South
3,4,2026-07-15,Ravi,Grocery,Sugar,5,3430,436,Cash,North
4,5,2026-07-26,Meena,Grocery,Rice,6,8748,1861,UPI,North
...,...,...,...,...,...,...,...,...,...,...
495,496,2026-01-20,Priya,Clothing,Jacket,8,15624,4630,Credit Card,North
496,497,2026-02-03,Priya,Grocery,Rice,7,8351,1690,Net Banking,East
497,498,2026-08-26,Ravi,Electronics,Headphones,8,174320,15477,Net Banking,North
498,499,2026-04-02,Rahul,Stationery,Marker,8,13336,2747,Debit Card,South
499,500,2026-04-17,Swathi,Clothing,Shoes,2,13882,2653,Net Banking,West

In [5]:
df.shape

(500, 10)

In [6]:
df.head()

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region
0,1,2026-07-08,Anu,Electronics,Laptop,5,167990,21688,Net Banking,North
1,2,2026-03-01,Nikhil,Stationery,File,1,111,11,Net Banking,North
2,3,2026-05-31,Akhil,Stationery,Pen,9,8181,1051,Cash,South
3,4,2026-07-15,Ravi,Grocery,Sugar,5,3430,436,Cash,North
4,5,2026-07-26,Meena,Grocery,Rice,6,8748,1861,UPI,North

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction_ID  500 non-null    int64
 1   Date            500 non-null    object
 2   Customer        500 non-null    object
 3   Category        500 non-null    object
 4   Product         500 non-null    object
 5   Quantity        500 non-null    int64
 6   Sales           500 non-null    int64
 7   Profit          500 non-null    int64
 8   Payment_Method  500 non-null    object
 9   Region          500 non-null    object
dtypes: int64(4), object(6)
memory usage: 39.2+ KB

In [8]:
df.describe()

       Transaction_ID    Quantity          Sales        Profit
count      500.000000  500.000000     500.000000     500.00000
mean       250.500000    5.588000   77935.808000   14718.44400
std        144.481833    2.884944  122810.672351   25053.37623
min          1.000000    1.000000     111.000000      11.00000
25%        125.750000    3.000000    6823.250000    1203.75000
50%        250.500000    6.000000   20646.000000    3654.00000
75%        375.250000    8.000000   94242.000000   16099.50000
max        500.000000   10.000000  747490.000000  156830.00000

In [9]:
df["Date"]=pd.to_datetime(df["Date"])

In [11]:
df.dtypes

Transaction_ID             int64
Date              datetime64[ns]
Customer                  object
Category                  object
Product                   object
Quantity                   int64
Sales                      int64
Profit                     int64
Payment_Method            object
Region                    object
dtype: object

In [12]:
df[df["Sales"]>5000]

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region
0,1,2026-07-08,Anu,Electronics,Laptop,5,167990,21688,Net Banking,North
2,3,2026-05-31,Akhil,Stationery,Pen,9,8181,1051,Cash,South
4,5,2026-07-26,Meena,Grocery,Rice,6,8748,1861,UPI,North
5,6,2026-06-08,Neha,Grocery,Rice,9,11250,2952,Net Banking,South
6,7,2026-08-07,Sneha,Electronics,Laptop,4,157720,46803,Cash,West
...,...,...,...,...,...,...,...,...,...,...
495,496,2026-01-20,Priya,Clothing,Jacket,8,15624,4630,Credit Card,North
496,497,2026-02-03,Priya,Grocery,Rice,7,8351,1690,Net Banking,East
497,498,2026-08-26,Ravi,Electronics,Headphones,8,174320,15477,Net Banking,North
498,499,2026-04-02,Rahul,Stationery,Marker,8,13336,2747,Debit Card,South
499,500,2026-04-17,Swathi,Clothing,Shoes,2,13882,2653,Net Banking,West

In [13]:
df[df["Profit"]>=15000]

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region
0,1,2026-07-08,Anu,Electronics,Laptop,5,167990,21688,Net Banking,North
6,7,2026-08-07,Sneha,Electronics,Laptop,4,157720,46803,Cash,West
10,11,2026-04-28,Vijay,Clothing,Dress,7,54229,15249,Debit Card,South
14,15,2026-04-22,Priya,Electronics,Keyboard,5,230435,24090,UPI,North
15,16,2026-08-11,Divya,Furniture,Desk,3,105813,29709,Net Banking,South
...,...,...,...,...,...,...,...,...,...,...
485,486,2026-04-09,Pooja,Electronics,Monitor,10,436840,83394,Net Banking,South
486,487,2026-02-04,Vijay,Furniture,Bookshelf,6,127668,22932,UPI,East
492,493,2026-07-10,Swathi,Furniture,Bookshelf,2,77646,20985,UPI,South
494,495,2026-08-22,Neha,Electronics,Headphones,4,238292,62574,Net Banking,South
497,498,2026-08-26,Ravi,Electronics,Headphones,8,174320,15477,Net Banking,North

In [14]:
df[df["Transaction_ID"]==7]

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region
6,7,2026-08-07,Sneha,Electronics,Laptop,4,157720,46803,Cash,West

In [15]:
df[(df["Profit"]>50000) & (df["Payment_Method"]=="UPI")]

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region
110,111,2026-04-25,Swathi,Furniture,Desk,10,340890,92162,UPI,East
118,119,2026-03-04,Nikhil,Electronics,Headphones,6,303786,53086,UPI,South
121,122,2026-04-19,Akhil,Electronics,Monitor,6,244260,53875,UPI,East
142,143,2026-01-28,Lakshmi,Electronics,Laptop,8,433120,75267,UPI,North
166,167,2026-07-14,Aditya,Electronics,Smartphone,8,498488,122617,UPI,East
179,180,2026-06-06,Divya,Electronics,Monitor,6,195798,57429,UPI,South
280,281,2026-04-30,Anu,Furniture,Sofa,6,213642,58584,UPI,East
343,344,2026-07-31,Kiran,Electronics,Keyboard,7,210357,61632,UPI,East
405,406,2026-02-12,Pooja,Electronics,Laptop,7,412566,99497,UPI,West
477,478,2026-05-24,Kiran,Electronics,Keyboard,10,414240,114257,UPI,East
480,481,2026-01-12,Priya,Furniture,Desk,9,238527,55925,UPI,South

In [16]:
df.sort_values("Sales")

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region
1,2,2026-03-01,Nikhil,Stationery,File,1,111,11,Net Banking,North
245,246,2026-08-26,Priya,Grocery,Rice,3,213,62,UPI,West
217,218,2026-06-14,Aditya,Stationery,Notebook,1,216,19,Debit Card,South
389,390,2026-02-05,Pooja,Stationery,File,1,229,32,Credit Card,South
48,49,2026-03-30,Ravi,Stationery,Marker,1,272,57,UPI,North
...,...,...,...,...,...,...,...,...,...,...
191,192,2026-05-10,Swathi,Electronics,Keyboard,9,611964,154833,Cash,West
287,288,2026-01-05,Arun,Electronics,Keyboard,10,648340,145904,Net Banking,West
157,158,2026-03-20,Meena,Electronics,Headphones,10,652830,127906,Credit Card,West
169,170,2026-05-29,Swathi,Electronics,Laptop,10,679620,111856,Cash,West
277,278,2026-02-23,Ravi,Electronics,Smartphone,10,747490,95487,Debit Card,North

In [18]:
df.sort_values("Profit")

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region
1,2,2026-03-01,Nikhil,Stationery,File,1,111,11,Net Banking,North
217,218,2026-06-14,Aditya,Stationery,Notebook,1,216,19,Debit Card,South
389,390,2026-02-05,Pooja,Stationery,File,1,229,32,Credit Card,South
48,49,2026-03-30,Ravi,Stationery,Marker,1,272,57,UPI,North
245,246,2026-08-26,Priya,Grocery,Rice,3,213,62,UPI,West
...,...,...,...,...,...,...,...,...,...,...
157,158,2026-03-20,Meena,Electronics,Headphones,10,652830,127906,Credit Card,West
287,288,2026-01-05,Arun,Electronics,Keyboard,10,648340,145904,Net Banking,West
473,474,2026-08-11,Priya,Electronics,Smartphone,9,567090,151646,Cash,West
191,192,2026-05-10,Swathi,Electronics,Keyboard,9,611964,154833,Cash,West
298,299,2026-03-25,Arun,Electronics,Headphones,10,534960,156830,Debit Card,West

In [19]:
df.groupby("Category")[["Sales","Profit"]].sum()

                Sales   Profit
Category
Clothing      2248310   444567
Electronics  22256321  4258542
Furniture    13063762  2399870
Grocery        797596   148153
Stationery     601915   108090

In [20]:
df.groupby("Product")["Sales"].sum()

Product
Biscuits        201050
Bookshelf      2564317
Calculator       80529
Chair          2367729
Cooking Oil     148934
Desk           3749482
Dress           676986
File            177259
Headphones     6651629
Jacket          440538
Jeans           398570
Keyboard       3210209
Laptop         4011847
Marker          120107
Monitor        2561259
Notebook         73943
Pen             150077
Rice            203758
Shirt           473960
Shoes           258256
Smartphone     5821377
Sofa           2264011
Sugar           129337
Table          2118223
Tea             114517
Name: Sales, dtype: int64

In [21]:
df.groupby("Product")[["Sales","Profit"]].sum()

               Sales   Profit
Product
Biscuits      201050    38848
Bookshelf    2564317   422466
Calculator     80529    18107
Chair        2367729   404371
Cooking Oil   148934    30229
Desk         3749482   737419
Dress         676986   134092
File          177259    29767
Headphones   6651629  1281498
Jacket        440538    85255
Jeans         398570    62054
Keyboard     3210209   693752
Laptop       4011847   661193
Marker        120107    20967
Monitor      2561259   496793
Notebook       73943    13938
Pen           150077    25311
Rice          203758    36717
Shirt         473960   107691
Shoes         258256    55475
Smartphone   5821377  1125306
Sofa         2264011   463610
Sugar         129337    25773
Table        2118223   372004
Tea           114517    16586

In [23]:
df.groupby("Product").agg(
    Total_Sales=("Sales","sum"),
    Total_Profit=("Profit","sum"),
    Total_Quantiyy=("Quantity","count"))

             Total_Sales  Total_Profit  Total_Quantiyy
Product
Biscuits          201050         38848              19
Bookshelf        2564317        422466              25
Calculator         80529         18107              13
Chair            2367729        404371              22
Cooking Oil       148934         30229              19
Desk             3749482        737419              27
Dress             676986        134092              23
File              177259         29767              28
Headphones       6651629       1281498              25
Jacket            440538         85255              22
Jeans             398570         62054              18
Keyboard         3210209        693752              13
Laptop           4011847        661193              19
Marker            120107         20967              17
Monitor          2561259        496793              17
Notebook           73943         13938              17
Pen               150077         25311              19
Rice              203758         36717              29
Shirt             473960        107691              17
Shoes             258256         55475              15
Smartphone       5821377       1125306              23
Sofa             2264011        463610              19
Sugar             129337         25773              20
Table            2118223        372004              21
Tea               114517         16586              13

In [24]:
Sales_report=df.groupby("Product").agg(
    Total_Sales=("Sales","sum"),
    Total_Profit=("Profit","sum"),
    Total_Quantiyy=("Quantity","count"))
Sales_report

             Total_Sales  Total_Profit  Total_Quantiyy
Product
Biscuits          201050         38848              19
Bookshelf        2564317        422466              25
Calculator         80529         18107              13
Chair            2367729        404371              22
Cooking Oil       148934         30229              19
Desk             3749482        737419              27
Dress             676986        134092              23
File              177259         29767              28
Headphones       6651629       1281498              25
Jacket            440538         85255              22
Jeans             398570         62054              18
Keyboard         3210209        693752              13
Laptop           4011847        661193              19
Marker            120107         20967              17
Monitor          2561259        496793              17
Notebook           73943         13938              17
Pen               150077         25311              19
Rice              203758         36717              29
Shirt             473960        107691              17
Shoes             258256         55475              15
Smartphone       5821377       1125306              23
Sofa             2264011        463610              19
Sugar             129337         25773              20
Table            2118223        372004              21
Tea               114517         16586              13

In [25]:
df.pivot_table(index="Product",
               columns="Region",
               values="Sales",
               aggfunc="sum")

Region          East    North    South     West
Product
Biscuits       52226    50493     6034    92297
Bookshelf     961756   497082   170050   935429
Calculator     23963    10151     7527    38888
Chair         260080  1189357   472940   445352
Cooking Oil    22207    49822    39713    37192
Desk         1280540   436004   766461  1266477
Dress         111722    59120   311966   194178
File           39960    55165    53980    28154
Headphones    810590  2790210  1235543  1815286
Jacket        111478    51200   111008   166852
Jeans         118516    10086   109434   160534
Keyboard      978893   344474   193608  1693234
Laptop        313071   645424   904350  2149002
Marker         53255    29463    26625    10764
Monitor       598103   295576   847515   820065
Notebook       30017     6169    22893    14864
Pen            51449    46146    15357    37125
Rice           45661    61647    18862    77588
Shirt         139245   108037   110006   116672
Shoes          90286    25500    58095    84375
Smartphone    811130  2023787  1502598  1483862
Sofa          549413   689499   509557   515542
Sugar          16092    36379    49422    27444
Table         403320   465370   480822   768711
Tea            35564    11568    16694    50691