In [9]:
import pandas as pd

In [12]:
df=pd.read_csv("financial_dataset.csv")

In [13]:
df

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,11317,CUST1134,Anjali,Furniture,1875.0,4126.0,16,Pending,Mumbai,2026-10-21 00:00:00
1,11001,CUST1177,Sneha,Stationery,32521.0,9290.0,13,Paid,Bangalore,2026-05-16 00:00:00
2,11069,CUST1478,Sneha,food,8948.0,8683.0,3,Unpaid,Chennai,2026-06-19 00:00:00
3,11968,CUST1016,Priya,Furniture,20072.0,8320.0,1,Pending,Mumbai,2027-09-11 12:00:00
4,10530,CUST1321,Priya,Stationery,32943.0,9336.0,3,Paid,Bangalore,2025-09-22 12:00:00
...,...,...,...,...,...,...,...,...,...,...
1995,10700,CUST1427,Rahul,Electronics,14407.0,9016.0,8,paid,Bangalore,2025-12-16 12:00:00
1996,11500,CUST1136,Neha,Electronics,2105.0,5292.0,13,Unpaid,Delhi,2027-01-20 12:00:00
1997,11706,CUST1247,Vivek,Food,35927.0,2756.0,5,Pending,Mangalore,2027-05-03 12:00:00
1998,10511,CUST1299,Rahul,Furniture,48447.0,1654.0,7,Unpaid,Delhi,2025-09-13 00:00:00
1999,11083,CUST1075,Arun,Clothing,8433.0,4718.0,5,Pending,Kochi,2026-06-26 00:00:00

In [14]:
df.head()

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,11317,CUST1134,Anjali,Furniture,1875.0,4126.0,16,Pending,Mumbai,2026-10-21 00:00:00
1,11001,CUST1177,Sneha,Stationery,32521.0,9290.0,13,Paid,Bangalore,2026-05-16 00:00:00
2,11069,CUST1478,Sneha,food,8948.0,8683.0,3,Unpaid,Chennai,2026-06-19 00:00:00
3,11968,CUST1016,Priya,Furniture,20072.0,8320.0,1,Pending,Mumbai,2027-09-11 12:00:00
4,10530,CUST1321,Priya,Stationery,32943.0,9336.0,3,Paid,Bangalore,2025-09-22 12:00:00

In [15]:
df.isnull().sum()

Transaction_ID       0
Customer_ID          0
Customer_Name        0
Category            23
Sales               33
Profit              30
Quantity             0
Payment_Status       0
City                21
Transaction_Date     0
dtype: int64

In [17]:
df["Profit"]=df["Profit"].fillna(df["Profit"].mean())

In [19]:
df["Sales"]=df["Sales"].fillna(df["Sales"].mean())

In [21]:
df["Payment_Status"]=df["Payment_Status"].fillna(df["Payment_Status"].mode()[0])

In [22]:
df["City"]=df["City"].fillna(df["City"].mode()[0])

In [25]:
df.duplicated().sum()

np.int64(40)

In [35]:
df=df.drop_duplicates()

In [38]:
df["City"]=df["City"].str.strip().str.title()

C:\Users\YAJNESH\AppData\Local\Temp\ipykernel_51124\1739747117.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["City"]=df["City"].str.strip().str.title()

In [39]:
df["Category"]=df["Category"].str.strip().str.title()

C:\Users\YAJNESH\AppData\Local\Temp\ipykernel_51124\3712819186.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Category"]=df["Category"].str.strip().str.title()

In [40]:
df["Payment_Status"]=df["Payment_Status"].str.strip().str.title()

C:\Users\YAJNESH\AppData\Local\Temp\ipykernel_51124\2894380703.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Payment_Status"]=df["Payment_Status"].str.strip().str.title()

In [43]:
df["Quantity"]=pd.to_datetime(df["Quantity"],errors="coerce")

C:\Users\YAJNESH\AppData\Local\Temp\ipykernel_51124\3711472440.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Quantity"]=pd.to_datetime(df["Quantity"],errors="coerce")

In [44]:
df.dtypes

Transaction_ID               int64
Customer_ID                 object
Customer_Name               object
Category                    object
Sales                      float64
Profit                     float64
Quantity            datetime64[ns]
Payment_Status              object
City                        object
Transaction_Date            object
dtype: object

In [45]:
print("Cleaned Financial dataset")

Cleaned Financial dataset

In [46]:
df

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,11317,CUST1134,Anjali,Furniture,1875.0,4126.0,1970-01-01 00:00:00.000000016,Pending,Mumbai,2026-10-21 00:00:00
1,11001,CUST1177,Sneha,Stationery,32521.0,9290.0,1970-01-01 00:00:00.000000013,Paid,Bangalore,2026-05-16 00:00:00
2,11069,CUST1478,Sneha,Food,8948.0,8683.0,1970-01-01 00:00:00.000000003,Unpaid,Chennai,2026-06-19 00:00:00
3,11968,CUST1016,Priya,Furniture,20072.0,8320.0,1970-01-01 00:00:00.000000001,Pending,Mumbai,2027-09-11 12:00:00
4,10530,CUST1321,Priya,Stationery,32943.0,9336.0,1970-01-01 00:00:00.000000003,Paid,Bangalore,2025-09-22 12:00:00
...,...,...,...,...,...,...,...,...,...,...
1995,10700,CUST1427,Rahul,Electronics,14407.0,9016.0,1970-01-01 00:00:00.000000008,Paid,Bangalore,2025-12-16 12:00:00
1996,11500,CUST1136,Neha,Electronics,2105.0,5292.0,1970-01-01 00:00:00.000000013,Unpaid,Delhi,2027-01-20 12:00:00
1997,11706,CUST1247,Vivek,Food,35927.0,2756.0,1970-01-01 00:00:00.000000005,Pending,Mangalore,2027-05-03 12:00:00
1998,10511,CUST1299,Rahul,Furniture,48447.0,1654.0,1970-01-01 00:00:00.000000007,Unpaid,Delhi,2025-09-13 00:00:00
1999,11083,CUST1075,Arun,Clothing,8433.0,4718.0,1970-01-01 00:00:00.000000005,Pending,Kochi,2026-06-26 00:00:00

In [47]:
df.to_csv("Cleaned_Financial_Transactions.csv")

In [48]:
df

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,11317,CUST1134,Anjali,Furniture,1875.0,4126.0,1970-01-01 00:00:00.000000016,Pending,Mumbai,2026-10-21 00:00:00
1,11001,CUST1177,Sneha,Stationery,32521.0,9290.0,1970-01-01 00:00:00.000000013,Paid,Bangalore,2026-05-16 00:00:00
2,11069,CUST1478,Sneha,Food,8948.0,8683.0,1970-01-01 00:00:00.000000003,Unpaid,Chennai,2026-06-19 00:00:00
3,11968,CUST1016,Priya,Furniture,20072.0,8320.0,1970-01-01 00:00:00.000000001,Pending,Mumbai,2027-09-11 12:00:00
4,10530,CUST1321,Priya,Stationery,32943.0,9336.0,1970-01-01 00:00:00.000000003,Paid,Bangalore,2025-09-22 12:00:00
...,...,...,...,...,...,...,...,...,...,...
1995,10700,CUST1427,Rahul,Electronics,14407.0,9016.0,1970-01-01 00:00:00.000000008,Paid,Bangalore,2025-12-16 12:00:00
1996,11500,CUST1136,Neha,Electronics,2105.0,5292.0,1970-01-01 00:00:00.000000013,Unpaid,Delhi,2027-01-20 12:00:00
1997,11706,CUST1247,Vivek,Food,35927.0,2756.0,1970-01-01 00:00:00.000000005,Pending,Mangalore,2027-05-03 12:00:00
1998,10511,CUST1299,Rahul,Furniture,48447.0,1654.0,1970-01-01 00:00:00.000000007,Unpaid,Delhi,2025-09-13 00:00:00
1999,11083,CUST1075,Arun,Clothing,8433.0,4718.0,1970-01-01 00:00:00.000000005,Pending,Kochi,2026-06-26 00:00:00